class_manager/class_manager/urls.py
from django.contrib import admin
from django.urls import path, include

import core.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", core.views.HomePageView.as_view(), name="homepage"),
    path('manager/', include('manager.urls', namespace='manager')),
]

class_manager/manager/urls.py
from django.urls import path

from . import views

app_name = "manager"

urlpatterns = [

    path("student/create", views.StudentCreateView.as_view(), name="student_create"),
    path("course/create", views.CourseCreateView.as_view(), name="course_create"),
    path("", views.CourseListView.as_view(), name="course_list"),
    path("students", views.StudentListView.as_view(), name="student_list"),
    path("course/<int:pk>", views.CourseDetailView.as_view(), name="course_detail"),
    path("student/<int:pk>", views.StudentDetailView.as_view(), name="student_detail"),
    path("course/delete/<int:pk>", views.CourseDeleteView.as_view(), name="course_delete"),
    path("student/delete/<int:pk>", views.StudentDeleteView.as_view(), name="student_delete"),
    path("course/update/<int:pk>", views.CourseUpdateView.as_view(), name="course_update"),
    path("student/update/<int:pk>", views.StudentUpdateView.as_view(), name="student_update"),
    path("student/update_bis/<int:pk>", views.StudentUpdatebisView.as_view(), name="student_update_bis",),
    path("course/update_bis/<int:pk>", views.CourseUpdatebisView.as_view(), name="course_update_bis"),
    path("student/bis/<int:pk>", views.StudentDetailbisView.as_view(), name="student_detail_bis"),
    path("course/bis/<int:pk>", views.CourseDetailbisView.as_view(), name="course_detail_bis"),
    path("student/js/<int:pk>", views.StudentDetailJsView.as_view(), name="student_detail_js"),
    path("course/js/<int:pk>", views.CourseDetailJsView.as_view(), name="course_detail_js")
    
]

class_manager/manager/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    name = models.CharField(max_length=50, unique=True)
    osis = models.IntegerField(unique=True, default='0000000')
    grade = models.SmallIntegerField(unique=False, default='9')
    gpa = models.FloatField(max_length=10, unique=False, default='100')

    class Meta:
        ordering = ['name']

    def __str__(self):
    		return self.name
        
        
class Course(models.Model):
    name = models.CharField(max_length=200, unique=True)
    teacher = models.CharField(max_length=200, unique=False)
    grade = models.SmallIntegerField(unique=False)
    students = models.ManyToManyField(Student)
    
    class Meta:
        ordering = ['name']

    def __str__(self):
    		return self.name

class_manager/manager/forms.py
from django import forms

from .models import Course

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'teacher', 'grade', 'students']
        widgets = {
        }
        
from .models import Student
  
class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'osis', 'grade', 'gpa']
        widgets = {
        }

class_manager/manager/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic.base import TemplateView

from .models import Course, Student
from django.forms.models import model_to_dict
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, JsonResponse

from .forms import CourseForm, StudentForm

# Create your views here.

### Course ###
class CourseListView(LoginRequiredMixin, ListView):
    model = Course

class CourseDetailView(DetailView):
    model = Course

class CourseCreateView(CreateView):
    model = Course
    form_class = CourseForm

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Course "{course_name}" has been created'.format(
                course_name=self.object.name))
        return response
    
    def get_success_url(self):
        return reverse_lazy("manager:course_detail", args=[self.object.id])
        
class CourseDeleteView(DeleteView):
    model = Course
    success_url = reverse_lazy("manager:course_list")
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Course "{course_name}" has been deleted'.format(
                course_name=self.object.name))
        return response

class CourseUpdateView(UpdateView):
    model = Course
    form_class = CourseForm

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Course "{course_name}" has been updated'.format(
                course_name=self.object.name
            ),
        )
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course_dico = model_to_dict(self.object)
        students = course_dico["students"]
        course_student_list = []
        for student in students:
            course_student_list.append({"id": student.id, "name": student.name})
            course_dico["students"] = course_student_list
            student_list = list(Student.objects.all().values())
            context["course_dico"] = course_dico
            context["student_list"] = student_list
            # print("context", context)
            return context
    
    def get_success_url(self):
        return reverse_lazy("manager:course_detail", args=[self.object.id])

class CourseUpdatebisView(View):
   def post(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=self.kwargs["pk"])
        # Create a form instance with POST data
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            return JsonResponse({"success": True})
        else:
            return JsonResponse({"success": False, "errors": form.errors})

class CourseDetailbisView(TemplateView):
    template_name = "manager/course_detailbis.html"
    
    def get(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=self.kwargs["pk"])
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course_id'] = self.kwargs["pk"]
        return context

class CourseDetailJsView(View):
    def get(self, request, *args, **kwargs):
        course = get_object_or_404(Course, pk=self.kwargs["pk"])
        course_js = model_to_dict(course)
        course_js["students"] = []
        for student in course.students.values():
            course_js["students"].append(student)
        return JsonResponse({"course": course_js})

### Student
class StudentListView(LoginRequiredMixin, ListView):
    model = Student


class StudentDetailView(DetailView):
    model = Student
    

class StudentCreateView(CreateView):
    model = Student
    form_class = StudentForm

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Student "{student_name}" has been created'.format(
                student_name=self.object.name))
        return response

    def get_success_url(self):
    	return reverse_lazy("manager:student_detail", args=[self.object.id])
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        student_dico = list(Student.objects.all().values())
        context["student_dico"] = student_dico
        # print("context", context)
        return context
 
class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy("manager:student_list")
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Student "{student_name}" has been deleted'.format(
                student_name=self.object.name))
        return response
 

class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Course "{student_name}" has been updated'.format(
                student_name=self.object.name))
        return response
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        student_dico = model_to_dict(self.object)
        context["student_dico"] = student_dico
        # print("context", context)
        return context

    def get_success_url(self):
        return reverse_lazy("manager:student_detail", args=[self.object.id])
    
class StudentUpdatebisView(View):
    def post(self, request, *args, **kwargs):
        student = get_object_or_404(Student, pk=self.kwargs["pk"])
        # Create a form instance with POST data
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return JsonResponse({"success": True})
        else:
            return JsonResponse({"success": False, "errors": form.errors})

class StudentDetailbisView(TemplateView):
    template_name = "manager/student_detailbis.html"
    
    def get(self, request, *args, **kwargs):
        student = get_object_or_404(Student, pk=self.kwargs["pk"])
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['student_id'] = self.kwargs["pk"]
        return context
    
class StudentDetailJsView(View):
    def get(self, request, *args, **kwargs):
        student = get_object_or_404(Student, pk=self.kwargs["pk"])
        student_js = model_to_dict(student)
        return JsonResponse({"student": student_js})

class_manager/manager/templates/manager/course_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete the course "{{ object.name }}"?</p>
    {{ form.as_p }}
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

class_manager/manager/templates/manager/course_detail.html
{% extends "base.html" %}
{% load django_vite %}
{% block content %}

<a href="{% url 'manager:student_list' %}">Students</a>
<a href="{% url 'manager:student_create' %}">Add Student</a><br>
<a href="{% url 'manager:course_list' %}">Courses</a>
<a href="{% url 'manager:course_create' %}">Add Course</a><br>
<a href="{% url 'manager:course_delete' object.id %}">Delete Course</a><br />
<a href="{% url 'manager:course_update' object.id %}">Update Course</a><br />

    <div id="app">
        <app>This is the course detail page</app>
    </div>

    <h1>{{ object.name }}</h1>
    Students:<br />
    {% for student in object.students.all %} {{student.name}}<br />
    {% endfor %}
    Teacher: {{object.teacher}}<br />
{% endblock content %}

class_manager/manager/templates/manager/course_detailbis.html
{% extends "base.html" %}

{% load django_vite %}

{% block content %}

    <div id="app">
        <app></app>
    </div>

{% endblock content %}

{% block js %}
    {{ block.super }} 
    <script>
        var ext_course_id = {{ course_id }}
        var ext_course_list_url = '{% url 'manager:course_list' %}'
        var ext_course_detail_js_url = '{% url 'manager:course_detail_js' course_id %}'
        var ext_course_update_url = '{% url 'manager:course_update' course_id %}'
        var ext_course_delete_url = '{% url 'manager:course_delete' course_id %}'
    </script>
    {% vite_hmr_client %}
    {% vite_asset 'src/apps/course_get/course_get.js' %} 
{% endblock js %}

class_manager/manager/templates/manager/course_form.html
{% extends "base.html" %}

{% load django_vite %}

{% block content %}

<a href="{% url 'manager:student_list' %}">Students</a>
<a href="{% url 'manager:student_create' %}">Add Student</a><br>
<a href="{% url 'manager:course_list' %}">Courses</a>
<a href="{% url 'manager:course_create' %}">Add Course</a><br>

<br />
<div id="app">
    <app></app>
</div>

{% endblock content %}

{% block js %}
    {{ block.super }} 
    <script>
        var ext_csrf_token = '{{ csrf_token }}'
        var ext_django_form = `{{ form.as_p | safe }}`
        var ext_course_dico = {{ course_dico | safe }} 
        var ext_student_list = {{ student_list | safe }}
        {% if request.resolver_match.url_name == 'course_create' %}
            var ext_update_bis_url = null;
        {% else %}
            var ext_update_bis_url = "{% url 'manager:course_update_bis' course.id %}";
        {% endif %}
    </script>
    {% vite_hmr_client %}
    {% vite_asset 'src/apps/course_post/course_post.js' %} 
{% endblock js %}

class_manager/manager/templates/manager/course_list.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'manager:student_list' %}">Students</a>
<a href="{% url 'manager:student_create' %}">Add Student</a><br>
<a href="{% url 'manager:course_list' %}">Courses</a>
<a href="{% url 'manager:course_create' %}">Add Course</a><br>

This is the course list page <br>

{% for course in object_list %}
<a href="{% url 'manager:course_detail_bis' course.id %}">{{ course.name }}</a><br/>
{% endfor %}

{% endblock content %}

class_manager/manager/templates/manager/student_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete the student "{{ object.name }}"?</p>
    {{ form.as_p }}
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

class_manager/manager/templates/manager/student_detail.html
{% extends "base.html" %}
{% load django_vite %}
{% block content %}

<a href="{% url 'manager:student_list' %}">Students</a>
<a href="{% url 'manager:student_create' %}">Add Student</a><br>
<a href="{% url 'manager:course_list' %}">Courses</a>
<a href="{% url 'manager:course_create' %}">Add Course</a><br>
<a href="{% url 'manager:student_delete' object.id %}">Delete Student</a><br />
<a href="{% url 'manager:student_update' object.id %}">Update Student</a><br />

    <div id="app">
        <app></app>
    </div>

    <h1>{{ object.name }}</h1>
    OSIS: {{object.osis}}<br />
    Grade: {{object.grade}}<br />
    GPA: {{object.gpa}}<br />

{% endblock content %}

class_manager/manager/templates/manager/student_detailbis.html
{% extends "base.html" %}

{% load django_vite %}

{% block content %}

    <div id="app">
        <app></app>
    </div>

{% endblock content %}

{% block js %}
    {{ block.super }} 
    <script>
        var ext_student_id = {{ student_id }}
        var ext_student_list_url = '{% url 'manager:student_list' %}'
        var ext_student_detail_js_url = '{% url 'manager:student_detail_js' student_id %}'
        var ext_student_update_url = '{% url 'manager:student_update' student_id %}'
        var ext_student_delete_url = '{% url 'manager:student_delete' student_id %}'
    </script>
    {% vite_hmr_client %}
    {% vite_asset 'src/apps/student_get/student_get.js' %} 
{% endblock js %}

class_manager/manager/templates/manager/student_form.html
{% extends "base.html" %}

{% load django_vite %}

{% block content %}

<a href="{% url 'manager:student_list' %}">Students</a>
<a href="{% url 'manager:student_create' %}"id="student_create">Add Student</a><br>
<a href="{% url 'manager:course_list' %}">Courses</a>
<a href="{% url 'manager:course_create' %}">Add Course</a><br>

<br />
<div id="app">
    <app></app>
</div>

{% endblock content %}

{% block js %}
    {{ block.super }} 
    <script>
        var ext_csrf_token = '{{ csrf_token }}'
        var ext_django_form = `{{ form.as_p | safe }}`
        var ext_student_dico = {{ student_dico | safe }} 
        var student_create = document.getElementById("student_create");

        {% if request.resolver_match.url_name == 'student_create' %}
            // Only include ext_update_bis_url if not on the "Add Student" page
            var ext_update_bis_url = null;
        {% else %}
            var ext_update_bis_url = "{% url 'manager:student_update_bis' student.id %}";
        {% endif %}
        
    </script>
    {% vite_hmr_client %}
    {% vite_asset 'src/apps/student_post/student_post.js' %} 
{% endblock js %}

class_manager/manager/templates/manager/student_list.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'manager:student_list' %}">Students</a>
<a href="{% url 'manager:student_create' %}">Add Student</a><br>
<a href="{% url 'manager:course_list' %}">Courses</a>
<a href="{% url 'manager:course_create' %}">Add Course</a><br>

This is the student list page <br />

{% for student in student_list %}
    <a href="{% url 'manager:student_detail_bis' student.id %}">{{ student.name }}</a><br/>
{% endfor %}

{% endblock content %}